PostgreSQL:
  restart: always
  image: postgres:12.0-alpine
  ports:
    - "5445:5445"
  environment:
    - DEBUG=false
    - POSTGRES_DB=store
  volumes:
    - ./modules/core/src/main/resources/tables.sql:/docker-entrypoint-initdb.d/init.sql

Redis:
  restart: always
  image: redis:5.0.0
  ports:
    - "6379:6379"
  environment:
    - DEBUG=false
